### ISSUE TITLE
Nothing todo with this script.

### ISSUE THREAD

**Issue by uGamers** [cl0ne/arch-packages#1]
Hi Clone im trying to use a script you made for HLTV Here https://gist.github.com/cl0ne/1117172 arch-adv.php 

Nice script! 

The only problem im having is where the demos are supposed to go for the webserver to show then on the premade page you made?

Any help i thank you!

Mark

**Comment by cl0ne** [comment]
Hello, Mark

`arch_mv.sh` is a script that can be run via cron. It cleans up old demos, archives new (age can be specified in days - see variable `OLDER_THAN`) and moves them to appropriate directory (array `OUT_PATH` entry matching source dir in `PATH_TO_DEMOS`).

That directory can be either local (in case you're hosting demos on the same physical server/VDS as your gameserver) or a mountpoint for remote directory of your webserver (e.g. use `curlftpfs` for ftp, also you can find solutions for mounting NFS/SMB/GoogleDrive etc.).

P.S. that gist has comments section and has no relation to arch-packages repo.
